site_name: YourGameLib
docs_dir: md_sites
site_dir: _deploy
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - plantuml_markdown
repo_url: https://github.com/duddel/yourgamelib
repo_name: duddel/yourgamelib
edit_uri: ""
nav:
  - Getting Started: index.md
  - Examples: Examples.md
  - Manual: Manual.md
  - API:
    - Overview: Overview.md
  - Development: Development.md
