list(APPEND YOURGAME_COMPILE_DEFS
  ELPP_STL_LOGGING
)

list(APPEND YOURGAME_INC_DIRS
  ${YOURGAME_EXT_PROJ_CODE_DIR}/easyloggingpp
)

list(APPEND YOURGAME_SRC_FILES
  ${YOURGAME_EXT_PROJ_CODE_DIR}/easyloggingpp/easylogging++.cc
)
