list(APPEND YOURGAME_INC_DIRS
  ${YOURGAME_EXT_PROJ_CODE_DIR}/stb
)

list(APPEND YOURGAME_SRC_FILES
  ${YOURGAME_EXT_PROJ_CODE_DIR}/stb/stb_vorbis.c
)

list(APPEND YOURGAME_COMPILE_DEFS
  STB_VORBIS_NO_STDIO
)
