name: docs
on: push

jobs:
  docs:
    name: build and deploy docs
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: install deps
        run: |
          sudo apt update
          sudo apt install doxygen plantuml
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          wget https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip
          unzip doxybook2-linux-amd64-v1.4.0.zip -d _doxybook2
      - name: run doxygen
        run: |
          cd docs
          doxygen --version
          doxygen
      - name: run doxybook2
        run: |
          cd docs
          # append the branch/tag name to the baseUrl for doxybook2, becuase the docs
          # are later moved there by mike (see below). ${GITHUB_REF##*/} is the actual
          # branch/tag name. double quotes (") around the sed substitute argument are
          # required for expanding ${GITHUB_REF##*/} before sed is executed.
          sed -i -E "s/(\"baseUrl\":\s*\".*)\"/\1${GITHUB_REF##*/}\/\"/g" doxybook_cfg.json
          ../_doxybook2/bin/doxybook2 --input _doxyout/xml/ --output ./md_sites --config ./doxybook_cfg.json
      - name: run mike
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global pull.rebase false
          git pull origin gh-pages --allow-unrelated-histories
          cd docs
          mike deploy ${GITHUB_REF##*/}
          cd ..
          git push origin gh-pages

  init:
    name: initialize project
    runs-on: ubuntu-20.04
    needs: docs

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: install python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: initialize
        run: |
          python ./init.py YourGameProject --clone
      - name: zip project
        run: |
          mkdir _deploy
          zip -r _deploy/YourGameProject.zip YourGameProject/
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: _deploy
          target-folder: ${{ env.GITHUB_REF_SLUG }}
          clean: false
