name: docs

on:
  push:
    branches:
      - master

jobs:
  build_examples:
    name: build web examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example_name: [framework]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: install python deps
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2
    - name: install emsdk
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: initialize
      run: |
        cd examples
        python ../tools/init.py ${{ matrix.example_name }} --noSources --extProj imgui
    - name: configure
      run: |
        source ./emsdk/emsdk_env.sh
        cd examples/${{ matrix.example_name }}
        mkdir _build
        cd _build
        emcmake cmake .. -DYOURGAME_PLATFORM=web
    - name: build
      run: |
        source ./emsdk/emsdk_env.sh
        cd examples/${{ matrix.example_name }}/_build
        emmake cmake --build .

    - name: prepare upload
      run: |
        cd examples/${{ matrix.example_name }}/_build
        mkdir _upload
        mv ./${{ matrix.example_name }}.* ./_upload
    - name: upload wasm artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.example_name }}
        path: examples/${{ matrix.example_name }}/_build/_upload

  docs:
    name: build and deploy docs
    needs: build_examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install deps
        run: |
          sudo apt update
          sudo apt install doxygen
      - name: build docs
        run: |
          cd docs
          doxygen

      - name: prepare deploy
        run: |
          mkdir _deploy
          cd _deploy
          mkdir examples
          mv ../docs/_doxyout/html/* ./

      - name: download wasm artifacts
        uses: actions/download-artifact@v1
        with:
          name: framework # todo: 2020-01-13 download framework example only, no "download-all" available
          path: _deploy/examples/

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _deploy
