name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: build_deploy_docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install deps
        run: |
          sudo apt update
          sudo apt install doxygen
      - name: build docs
        run: |
          cd docs
          doxygen

      - name: install emsdk
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: configure example
        run: |
          source ./emsdk/emsdk_env.sh
          cd examples/framework
          mkdir _build
          cd _build
          emconfigure cmake -DYOURGAME_PLATFORM=wasm ..
      - name: build example
        run: |
          source ./emsdk/emsdk_env.sh
          cd examples/framework/_build
          emmake cmake --build .

      - name: prepare deploy
        run: |
          mkdir _deploy
          cd _deploy
          mkdir framework
          mv ../examples/framework/_build/framework.* framework/
          mv ../docs/_doxyout/html/* ./
          cd framework
          mv framework.html index.html

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _deploy
