name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: build and deploy docs
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt update
          sudo apt install doxygen
      - name: build docs
        run: |
          cd docs
          doxygen
      - name: prepare deploy
        run: |
          mkdir _deploy
          cd _deploy
          mv ../docs/_doxyout/html/* ./
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _deploy
