name: examples

on: push

jobs:
  build_examples_desktop:
    name: desktop

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]
        example_name: [framework,GameMenu,bare]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: install python deps
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2
    - name: install deps
      run: |
        sudo apt update
        sudo apt install libgl1-mesa-dev xorg-dev
      if: startsWith(matrix.os, 'ubuntu')
    - name: initialize (ubuntu)
      run: |
        cd examples/${{ matrix.example_name }}
        ./init.bash
      if: startsWith(matrix.os, 'ubuntu')
    - name: initialize (windows)
      run: |
        cd examples/${{ matrix.example_name }}
        init.cmd
      if: startsWith(matrix.os, 'windows')
      shell: cmd
    - name: configure
      run: |
        cd examples/${{ matrix.example_name }}
        mkdir _build
        cd _build
        cmake -DYOURGAME_PLATFORM=desktop ..
    - name: build
      run: |
        cd examples/${{ matrix.example_name }}/_build
        cmake --build .


  build_examples_web:
    name: web

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        example_name: [framework,GameMenu,bare]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: install python deps
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2
    - name: install emsdk
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: initialize
      run: |
        cd examples/${{ matrix.example_name }}
        ./init.bash
    - name: configure
      run: |
        source ./emsdk/emsdk_env.sh
        cd examples/${{ matrix.example_name }}
        mkdir _build
        cd _build
        emcmake cmake .. -DYOURGAME_PLATFORM=web
    - name: build
      run: |
        source ./emsdk/emsdk_env.sh
        cd examples/${{ matrix.example_name }}/_build
        emmake cmake --build .


  build_examples_android:
    name: android

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        example_name: [framework,GameMenu,bare]

    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.5'
    - name: install python deps
      run: |
        python -m pip install --upgrade pip
        pip install Jinja2
    - name: initialize
      run: |
        cd examples/${{ matrix.example_name }}
        ./init.bash
    - name: assemble
      run: |
        cd examples/${{ matrix.example_name }}/android
        ./gradlew assembleDebug
