name: mainCI

on: push

jobs:
  build:
    name: examples

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]
        example_name: [mini-gl, framework]

    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt install libgl1-mesa-dev xorg-dev
      if: startsWith(matrix.os, 'ubuntu')
    - name: ${{ matrix.example_name }} configure
      run: |
        cd examples/${{ matrix.example_name }}
        mkdir _build
        cd _build
        cmake ..
    - name: ${{ matrix.example_name }} build
      run: |
        cd examples/${{ matrix.example_name }}/_build
        cmake --build .
