name: mainCI

on: push

jobs:
  build:
    name: examples

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, windows-2016, windows-2019]

    steps:
    - uses: actions/checkout@v1
    - name: install deps
      run: sudo apt install libgl1-mesa-dev xorg-dev
      if: startsWith(matrix.os, 'ubuntu')
    - name: mini-gl configure
      run: |
        cd examples/mini-gl
        mkdir _build
        cd _build
        cmake ..
    - name: mini-gl build
      run: |
        cd examples/mini-gl/_build
        cmake --build .
