name: tests
on: push

jobs:
  build_run_tests:
    name: build/run tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, windows-2022]

    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-dev xorg-dev
        if: startsWith(matrix.os, 'ubuntu')
      - name: configure
        run: |
          cd test
          mkdir _build
          cd _build
          cmake ..
      - name: build
        run: |
          cd test/_build
          cmake --build .
      - name: run
        run: |
          cd test/_build
          # -C Debug: chose "Debug" if multiple build configs available,
          # like in Visual Studio Solutions, -V: verbose output
          ctest -C Debug -V
